ADD_SCENE(pi_terminal, start, Start)
ADD_SCENE(pi_terminal, setup, Setup)
ADD_SCENE(pi_terminal, console_output, ConsoleOutput)
ADD_SCENE(pi_terminal, text_input, UART_TextInput)
ADD_SCENE(pi_terminal, hex_input, UART_HexInput)
ADD_SCENE(pi_terminal, help, Help)
